apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appserver.service.name }}
spec:
  type: {{ .Values.appserver.service.type }}
  selector:
    app: hello
  ports:
    - name: http
      protocol: TCP
      port: 80
